### ISSUE TITLE
[Tap To Pay] Reader has been disconnected unexpectedly on Android devices

### ISSUE THREAD

**Issue by ThanJack** [stripe/stripe-terminal-react-native#693]
**Describe the bug**
After putting the Android app in the background for some time, then reopening the app to do the first Tap to Pay transaction causes the following issue happens:
```
[Stripe terminal]: didReportUnexpectedReaderDisconnect { message: 'Reader has been disconnected unexpectedly',
  code: 'UNEXPECTED_ERROR.UNEXPECTED_SDK_ERROR' }
```
It happened after after creating the Payment Intent by the `createPaymentIntent` function and before the `collectingPaymentMethod` function executes. Then the `collectingPaymentMethod` function throws this error, which causes the transaction to fail:
```
{ code: 'INTEGRATION_ERROR.NOT_CONNECTED_TO_READER',
  message: 'LocalMobile reader is not connected' }
```

**To Reproduce**

1. Put app to the background for a while (eg. more than 2 hours). 
2. Reopen the app, start the first transaction.
3. Tap To Pay screen appears, try to tap a card.
4. The issue above happens.

**Expected behavior**

The Reader should not be disconnected unexpectedly when doing the transaction.

**Stripe Terminal React Native SDK version**

- `^0.0.1-beta.17`
- `^0.0.1-beta.18`

**Smartphone (please complete the following information):**

- Device: Google Pixel 3a
- OS: Android 12

**Comment by tzecheng** [comment]
Hi,
It also happens on a Pixel 4, running Android 13.
Note that the error is random.  We left the app in the background over multiple periods, sometimes the payment works on re-opening the app, sometimes the above error happens.

**Comment by nazli-stripe** [comment]
@tzecheng and @ThanJack can you share account and serial numbers so we can investigate?

**Comment by tzecheng** [comment]
Hi @nazli-stripe , I can't find the account and serial numbers when the payment is cancelled.

The latest has id: pi_3PF7CwEcr8OExvfT1zxs98vO

Attached bugfender screen shot
[android cancelled 4.pdf](https://github.com/stripe/stripe-terminal-react-native/files/15302725/android.cancelled.4.pdf)

Hope that helps.  Thanks.

**Comment by KillianLarcher** [comment]
> It also happens on a Pixel 4, running Android 13.
> Note that the error is random. We left the app in the background over multiple periods, sometimes the payment works on re-opening the app, sometimes the above error happens.

Same problem here on Samsung Tab Active 3, running Android 13.

**Comment by nazli-stripe** [comment]
This appears to be a potential issue with our native Android SDK, we are investigating internally. Will update this ticket with new information

**Comment by tzecheng** [comment]
Hi @nazli-stripe ,

This is one of the latest instances where there is a serial number:
 serialNumber: '7808ed1a-4ea0-4f73-9c83-5a7bc28a04f4'

**Comment by tzecheng** [comment]
Here's another serial number:
serialNumber: 'b7c812c4-0237-4b3b-9366-cc9318004df0'

**Comment by KillianLarcher** [comment]
Any news? @nazli-stripe

**Comment by tzecheng** [comment]
Hello, @nazli-stripe ,
Any progress on this?

**Comment by tzecheng** [comment]
Hi there,
Here's is a screenshot of latest failure,
Serial number: 6b16a116-d082-4568-af55-34e1104bdf3a

![Android bg failure](https://github.com/stripe/stripe-terminal-react-native/assets/43035024/d8df10c5-9771-469e-9c46-d3d91ebde1ef)

**Comment by tzecheng** [comment]
Hi there,

Have tried with
^0.0.1-beta.19 and ^0.0.1-beta.20

Problem is still there.
Latest serialNumber: '2e941d93-52cb-4eea-a3db-9fbe1ecd1c13'
![Screenshot 2024-09-09 at 4 45 54 PM](https://github.com/user-attachments/assets/4aa6214f-a431-48d7-8216-24b56307f40e)

**Comment by nabilfreeman** [comment]
We are also experiencing this. The only solution so far has been to disconnect and reconnect the reader every time we want to initiate Tap to Pay. It looks like the library is unable to monitor the connection state of the reader in background and reconnect properly.

**Comment by tzecheng** [comment]
Hi there,
Have updated to v0.0.1-beta.22, but this problem still appears occasionally.
Latest serial no:
![Screenshot 2024-10-24 at 11 46 23 PM](https://github.com/user-attachments/assets/dce16406-5bab-4eac-8f73-f29b7678f982)

**Comment by nazli-stripe** [comment]
hey sorry for the radio silence on this one, we just released beta.23 with upgrades to the native Android SDK. Do you run into the issue there as well?

**Comment by nazli-stripe** [comment]
@tzecheng did updating to beta.22 help with the occurrences of the issue?

**Comment by tzecheng** [comment]
Hi @nazli-stripe ,

Problem still happening in v0.0.1-beta.22, as mentioned in an earlier chat https://github.com/stripe/stripe-terminal-react-native/issues/693#issuecomment-2435664847

Will be testing with v0.0.1-beta.23 next week.

Thanks.

**Comment by tzecheng** [comment]
Hi @nazli-stripe ,

We updated to v0.0.1-beta.23, but unfortunately the error is still there.

1. First tap - it errors, the white Tap to Pay screen does not appear
2. App goes back to the payment screen - the amount is still there
3. Second tap - the white Tap to Pay screen appears, tap the card to the back of the phone and it completes

Latest error:
payment_intent_id: 'pi_3QPxgUEсr80ExvfT1oaFUjK6
serialNumber: '0cb69f75-032f-4863-b2a6-7b7a9ed4e4ab'

[android bg error.pdf](https://github.com/user-attachments/files/17942278/android.bg.error.pdf)

**Comment by tzecheng** [comment]
Hi @KillianLarcher , @nabilfreeman ,
Not sure whether I should post this here:
Did you manage to find a work around for this and would you mind sharing it? 
Users are finding this is frustrating especially when they need to take a payment quickly.
We show them an error modal and ask them to retry again which works, but it is still annoying.

cc: @nazli-stripe

**Comment by nabilfreeman** [comment]
@tzecheng the solution for us has been to disconnect the reader after every success/failure and make sure we are connecting from scratch whenever the user initiates the payment flow.

I mentioned this above in a comment a few months back - it seems that there are some issues with the library maintaining a synchronised connection state with the OS.

This is not necessary on iOS, but the Android side has a lot of Tap to Pay bugs and a degraded experience. See #809 for more problems

Worth understanding that this library is a wrapper for closed-source iOS and Android SDKs, which are often several versions ahead of the pinned version here, so it’s very difficult for us to debug.

**Comment by tzecheng** [comment]
Hi @nazli-stripe ,

We did some further testing with v0.0.1-beta.23 and this is our observation:

1. In our onDidReportUnexpectedReaderDisconnect callback, we remove our codes to disconnect any existing readers, then to discover and connect to readers - basically let the Stripe SDK handle the reconnects
2. On coming from background, we start a payment
3. onDidChangeConnectionStatus shows the reader trying to connect → happens 3 times
4. At this point, the payment intent returns a timeout about a second later
5. [Stripe terminal]: didChangeConnectionStatus now connects → appears about 5 seconds later
6. Now retrying the payment works since reader is now available
7. Note the timing is from our app, and will not apply across board

Our guess is that in our case, when coming from background or when network is reconnecting, the reader takes time to connect, but the payment intent has timed out.

**Comment by chr-stripe** [comment]
Hi all! Hope you've had a pleasant holiday season.

The Tap to Pay on Android SDK runs mostly in a separate process for security purposes. It is expected that if the application is in a backgrounded state for some time, the Android device may begin to clear out processes that are backgrounded in order to reclaim memory and resources for other foregrounded applications. If this happens, the connection to the Tap to Pay reader will be lost, and will require a manual reconnection if not opting into [automatic reconnections](https://docs.stripe.com/terminal/payments/connect-reader?terminal-sdk-platform=android&reader-type=tap-to-pay#automatically-attempt-reconnection) provided by the SDK.

@tzecheng glad to hear that allowing the SDK to handle the reconnection has worked out for you. One thing I want to confirm with you is if the SDK is reporting that the reader is disconnected before or _after_ you attempt you attempt to collect a new payment. In other words, is `getConnectionStatus()` still resolving to `connected` before you try to start a payment and receive the not connected exception, or does it accurately report `notConnected` (or possibly `connecting` if using automatic reconnects)? This should be reported to your application at the moment when the Tap to Pay reader disconnects, so you could use this value to determine if a connection to the reader is still established or not.

If you are able to reproduce this issue again, providing the payment intent id and/or the reader serial number + approximate time of the failure will help for me to check our own internal logs that may be recorded when this happens.

**Comment by tzecheng** [comment]
Hi @chr-stripe ,

I have attached several screenshots from Bugfender (hope it is not an overkill).  This happened yesterday morning when I woke up the phone to start a payment (this is against the Stripe test database).  Please let us know whether we are on the right track or not.

This happens in both production and test.

[android bg fail 1.pdf](https://github.com/user-attachments/files/18400424/android.bg.fail.1.pdf)

Thanks.
